sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-contributions@amazon.com
      - travis-build@platform-notifications.robomaker.aws.a2z.com
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
  global:
    - AFTER_SCRIPT='if [ -z "$PRERELEASE" ] || [ "$PRERELEASE" != true ]; then cd ~/catkin_ws && catkin build --pre-clean --catkin-make-args run_tests && catkin_test_results --verbose; fi;'
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ros_ci
script:
  - .ros_ci/travis.sh
